services:
  django:
    build: .
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      # See docker-compose.override.example.yml on how to to override these
      DJANGO_SETTINGS_MODULE: modernomad.settings
      DATABASE_URL: psql://postgres:postgres@postgres:5432/postgres
      STRIPE_SECRET_KEY: xxx
      STRIPE_PUBLISHABLE_KEY: xxx
      MAILGUN_API_KEY: xxx
      DEBUG: 1
      LOCALDEV: 1
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"

  client:
    build:
      context: client  # Dockerfile is inside client dir
    command: ["node", "server.js"]
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
      - "/app/client/node_modules"

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
